# Generated by Django 2.2.12 on 2020-05-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeno_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZenoUpload',
        ),
    ]
