# Generated by Django 3.0.5 on 2020-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeno_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZenoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
