# Generated by Django 2.2.12 on 2020-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeno_api', '0002_delete_zenoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenocsv',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
