# Generated by Django 2.2.12 on 2020-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeno_api', '0002_zenoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenocsv',
            name='_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='zenocsv',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
