# Generated by Django 2.2.12 on 2020-05-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeno_api', '0003_auto_20200501_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zenocsv',
            old_name='_id',
            new_name='idd',
        ),
    ]
